TEST_SYSTEM_URL: "https://opensource-demo.orangehrmlive.com/web/index.php/auth/login"
RESET_PASS_URL: "https://opensource-demo.orangehrmlive.com/web/index.php/auth/requestPasswordResetCode"
SEND_RESET_PASS_URL: "https://opensource-demo.orangehrmlive.com/web/index.php/auth/sendPasswordReset"
USERS_URL: "https://opensource-demo.orangehrmlive.com/web/index.php/admin/viewSystemUsers"