LOGIN_SYSTEM_URL: "http://localhost:3000/"
REGISTER_SYSTEM_URL: "http://localhost:3000/register"

RESET_PASS_URL: "https://opensource-demo.orangehrmlive.com/web/index.php/auth/requestPasswordResetCode"
SEND_RESET_PASS_URL: "https://opensource-demo.orangehrmlive.com/web/index.php/auth/sendPasswordReset"
USERS_URL: "https://opensource-demo.orangehrmlive.com/web/index.php/admin/viewSystemUsers"